### ISSUE TITLE
`memsocket::Socket::new()` over `memsocket::new()` for creation?

### ISSUE THREAD

**Issue by Hoverbear** [alyssais/memsocket#1]
It's fairly common for structures to have `Self::new()` over having it as an unattached function like `new()`. One exception is `mpsc::channel()`. (https://doc.rust-lang.org/std/sync/mpsc/index.html)

**Comment by alyssais** [comment]
Hi Hoverbear! :D 

I'm aware of the `Self::new()` convention but decided not to use it in this case because I don't want to have a way to instantiate a single `Socket`, only a matching pair, much like the `mpsc::channel()` example you bring up. Does that make sense? Or are there examples of a `Self::new()` returning a matching pair I should look at as well?

**Comment by Hoverbear** [comment]
:wave: 

Maybe something like `memsocket::pair()` or `memsocket::Socket::pair()`? I've seen `fn new() -> Result<_, _>`, but I don't  see tuple pairs frequently returned.
